### ISSUE TITLE
device inbuilt scanner says virus

### ISSUE THREAD

**Issue by Unacceptium** [puutaro/CommandClick#11]
i have installed today version just because i dont kniw what this app can do. but i didnt even started the app, this screen welcomed me:
![Screenshot_20240226_075213](https://github.com/puutaro/CommandClick/assets/145642963/9db1f480-6c57-4dbf-946a-bb8a30aa1f17)
i hooe this is a fake information because the android's scanner is known for that...

edit: the screen says virus apllication found wich sends private sms and bla bla.. just in an alien language

**Comment by puutaro** [comment]
Thank you for your point out.  
In conclusion, this app don't virus app. 
But, this has sensitive permission like bellow.  

> ACCESS_FINE_LOCATION -> Ths require WIFI setting via QR reader .
> READ_EXTERNAL_STORAGE -> CommandClick base is file system. This app data is saved to file. So, without this permission, CC is not feasible.

ref [issue](https://github.com/puutaro/CommandClick/issues/10)

In addition to this, CommandClick can handle SMS contents to other app. via QR reader feature.  

CommandClick has multiple feature like "army knife" browser.    
The functions of this app are not only browser and ubuntu, but also QR reader and low code tool functions.　　
That's why some features are sensitive. It's not a virus app at all.

**Comment by Unacceptium** [comment]
thamks for clarification
