### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by pouek** [puutaro/CommandClick#5]
Hi,
I've just installed v0.0.41 from f-droid with izzyOnDroid repo, and the app won't open, instantly crashes.
I get this error dump :

java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:1399)
	at ...

I read on this error that colors need to be passed with Hex codes.

Maybe this can help.

Ask for full error dump.

Pouek

**Comment by puutaro** [comment]
Thank you for download and pointint out. This problem is found yesterday, and I fix at [this v0.0.42 release](https://github.com/puutaro/CommandClick/releases/tag/v0.0.42)  .
When reinastalling , I recomend  that you delete `cmdclick` directory at `/document/cmdclick` becuase of previous miss settting leaving.
I wish `CommandClick` change your browser life and app life.

**Comment by pouek** [comment]
Hi, thank you for your effort, and reactivity.
The app seems still in early alpha stage :
The workflow and documentation aren't easy to understand at all.
Maybe should you get help, or wait to have a more finished app before publishing ?
I hope I'm wrong, and that it's going to be a useful tool, as it promises to !
I'll keep an eye on it !

**Comment by puutaro** [comment]
> Maybe should you get help, or wait to have a more finished app before publishing ?

About above pointing out,   
Your suggest is that anyone can coming up with. But this is not case, becuase `CommmandClick` don't have license violation and other a law violation.
Also, If only finished and easy application should publish, innovation  stagnate.  
I mean,  `CommandClick` locate near innovation.  
Attendantly please read [this](https://github.com/puutaro/CommandClick#generally-troubleshooting) sentence

> When fannel suddenly not working, update latest `CommandClick` and `fannel`.
>
> `CommandClick` and fannel is new baby. Therefore, these is frequetly updated without backwards compatible.　I continuly >enforce usability and fanctionality. Before long, if these grow up adult, I weight stability. But, please feel at ease, most often even now, latest version works fine.

`CommandClick`  first start `termux` client. but concentrating `termux` cuase slow speed, and limited use case. Of couse, `termux` client is admirable one, and it is more simple workflow, more simple doumentation, except for limited usecase.   
Then I cannot satisfied, I hope `CommandClick` support my daily use like browser and etc. So, add webView feature to `CommandClick`. More, Pull android os feature, and java or kotlin library power like `webview` javascript interface through `webview`. As a result, instead of complicated structure, `CommandClick` go over limited useage. More no just get browser feature but also own multiple application feature, more speaking low code tool feature.
Current `CommandClick` may be not suit for your demand level, from point of  your view, documentation is not easy, workflow is not simple. Becuase  `CommandClick` is not simple browser, javascript client, android os feature client and termux client. More speaking expanding feature daily. 
Threfore, `CommandClick` development is not steady. But that is `CommandClick`' instinct. Expanding itself may be `CommandClick`.
Of course, your hope is natural. so, at the right time I change document structure(graphical ui description and separate detail to another link, add tutorial), and measure about workflow(change ui).
I would appreciate it if you could keep checking the growth of `CommandClick`.
Thank you.

**Comment by puutaro** [comment]
ping @pouek
