### ISSUE TITLE
signing issue

### ISSUE THREAD

**Issue by IzzySoft** [puutaro/CommandClick#6]
Todays release reports to be signed with a different key, which not only breaks updates but also raises security concerns. The release notes give no hint. Mind to outline what happened? Until solved, updates won't be listed at IzzyOnDroid as they are rejected due to this fact.

**Comment by puutaro** [comment]
Thank you for report.  
Becuase I hadn't done a release build for a while and it looked like the key was gone, I re-create new key. Therefore This is the author's handiwork and is not an unauthorized publication.

**Comment by IzzySoft** [comment]
Thanks for confirming! Two questions:

* you write "it looked like the key was gone". So you found it meanwhile?
* if you found it: could you switch back to the known signature, please? Else folks having a previous version installed not only cannot update without uninstalling and reinstalling – but they won't even get a notification for that.
* if it's really lost: no offense meant, but can we somehow prove it's really you? An "unauthorized publisher" could say the very same.

For details, please see: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/de/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)

**Comment by puutaro** [comment]
I re-create [release](https://github.com/puutaro/CommandClick/releases/tag/v0.0.53) by correct key, and delete  new key's one.    
I are planning to add a large-scale feature this time, I mean, adding `Ubuntu` to `CommandClick`'s backend.　
Because of that, I had so much to do that I didn't have time to look at master for a while.
Then, when I was renovating the master branch for the first time in a while, I watch  a different generate screen than usual appeared and it seemed a little confusing. 
In any case, I think it was re-generated with the correct key.  
Thank you.

**Comment by IzzySoft** [comment]
That one looks good, thanks! Had to manually pull the APK from behind your link, as Github once more messed up: you tapped into a know trap here, replacing a tag (take a look at [Releases](https://github.com/puutaro/CommandClick/releases) to see what I mean: good luck finding your new one. You even got the "full house": It's not listed at all if you do not have the direct link to it; usually it's just hidden somewhere in the middle, on page 2 or 3).

Thanks for re-establishing the original keystore! I've already pulled in the APK so it goes live in about an hour here. Even if this one tag/release seems to be "hidden" (it can be found via the [Tags](https://github.com/puutaro/CommandClick/tags) page, though), new tags/releases won't be affected – so issue is solved :smiley:
